serve:
  port: 80
  browser: false
  playground: true
  endpoint: /solaredge
  playgroundTitle: Solar Edge Playground

sources:
  - name: P1METER
    handler:
      jsonSchema:
        endpoint: http://p1mon.internal.anjokolkcom:82
        operations:
          - type: Query
            field: p1meter
            path: /
            method: GET
            responseSample: ./jsons/p1meter.response.json
            responseTypeName: P1Meter
  - name: SOLAR
    handler:
      jsonSchema:
        endpoint: https://monitoringapi.solaredge.com/
        queryParams:
          api_key: '{env.SOLAREDGE_KEY}'
        operations:
          - type: Query
            field: Sites
            path: /sites/list.json
            method: GET
            responseSample: ./jsons/SiteList.response.json
            responseTypeName: SiteList
          - type: Query
            field: SiteDetails
            path: /site/{env.SOLAREDGE_SITEID}/details.json
            method: GET
            responseSample: ./jsons/SiteDetails.response.json
            responseTypeName: SiteDetail
          - type: Query
            field: Inventory
            path: /site/{env.SOLAREDGE_SITEID}/inventory.json
            method: GET
            responseSample: ./jsons/inventory.response.json
            responseTypeName: Inventory
          - type: Query
            field: EquipmentData
            path: /equipment/{env.SOLAREDGE_SITEID}/{args.serialno}/data.json?startTime={args.startTime}&endTime={args.endTime}
            argTypeMap:
              serialno:
                type: string
                nullable: false
              startTime:
                type: string
                nullable: false
              endTime:
                type: string
                nullable: false
            method: GET
            responseSample: ./jsons/equipmentdata.response.json
            responseTypeName: EquipmentData            
            
    transforms:
      - prefix:
          value: SOLAR
          includeRootOperations: true
