version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
